services:
  otel-lgtm:
    image: grafana/otel-lgtm:latest
    ports:
      - "3000:3000" # Grafana (http://localhost:3000/). User: admin, password: admin
      - "4040:4040" # Pyroscope endpoint
      - "4317:4317" # OpenTelemetry GRPC endpoint
      - "4318:4318" # OpenTelemetry HTTP endpoint
      - "9090:9090" # Prometheus endpoint
    expose:
      - "3000"
    volumes:
      - otel-lgtm-data:/data
    networks:
      default:
        aliases:
          - jaeger
          - otel-collector
          - prometheus

volumes:
  otel-lgtm-data:
    driver: local

networks:
  default:
    driver: bridge
