database:
  conn-max-lifetime: 1h0m0s
  dsn: db.sqlite
  max-idle-conss: 2
  max-open-conns: 0
  type: sqlite
initialize:
  admin:
    password: ""
    username: ""
log:
  format: text
  level: debug
  report-caller: false
mdns:
  hostname: mechanus
  ipv6: false
  servicetype: _http._tcp.local
otel:
  enabled: false
  endpoint: localhost:4318
  insecure: true
  service-name: mechanus-server
server:
  cors:
    allow-localhost: true
    allowed-origins:
      - "*"
  host: ""
  port: 8080
  static:
    folder: ../client/build

