name: ğŸšš Release assets

on:
  release:
    types: [released]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    name: ğŸ³ Build & Push Docker Image
    permissions:
      contents: write # For updating the release
      packages: write # Required for pushing to ghcr.io
      id-token: write # OIDC token if needed

    steps:
      - name: ğŸ“¦ Checkout Repository
        uses: actions/checkout@v4

      - name: âš’ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ”‘ Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ› ï¸ Build and Push
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/mechanus:latest
            ghcr.io/${{ github.repository_owner }}/mechanus:${{ github.event.release.tag_name }}

      - name: ğŸ“Œ Update Release Notes with Docker Image
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          body: |
            ${{ github.event.release.body }}

            ---
            ğŸ³ **Docker images for this release:**
            - `ghcr.io/${{ github.repository_owner }}/mechanus:latest`
            - `ghcr.io/${{ github.repository_owner }}/mechanus:${{ github.event.release.tag_name }}`
